import { PUBLIC_URL } from 'src/configs';

export const IMAGE_PATH = {
  FREETRIAL: `${PUBLIC_URL}/images/FreeTrial.png`,
  FREETRIAL_ELEMENT: `${PUBLIC_URL}/images/FreeTrial_element.svg`,
  IMAGE_BIRD: `${PUBLIC_URL}/images/bird.jpg`,
  LOGO_FOOTER: `${PUBLIC_URL}/images/logo-footer.svg`,
  LOGO_ORANGE: `${PUBLIC_URL}/images/logo-orange.svg`,
  LOGO_WHITE: `${PUBLIC_URL}/images/logo-white.svg`,
  USA: `${PUBLIC_URL}/images/usa.svg`,
  VN: `${PUBLIC_URL}/images/vn.svg`,
  VIDEO: `${PUBLIC_URL}/images/home/video.svg`,
  ITEM1: `${PUBLIC_URL}/images/home/item1.svg`,
  ITEM2: `${PUBLIC_URL}/images/home/item2.svg`,
  ITEM3: `${PUBLIC_URL}/images/home/item3.svg`,
  ITEM4: `${PUBLIC_URL}/images/home/item4.svg`,
  ITEM5: `${PUBLIC_URL}/images/home/item5.svg`,
  ITEM6: `${PUBLIC_URL}/images/home/item6.svg`,
  ITEM7: `${PUBLIC_URL}/images/home/item7.svg`,
  ITEM8: `${PUBLIC_URL}/images/home/item8.svg`,
  ITEM9: `${PUBLIC_URL}/images/home/item9.svg`,
  POLYGON: `${PUBLIC_URL}/images/home/polygon.png`,
  AWARD: `${PUBLIC_URL}/images/home/award.svg`,
  VTV: `${PUBLIC_URL}/images/home/vtvcab.svg`,
  VIETTEL: `${PUBLIC_URL}/images/home/viettel.svg`,
  TRUE: `${PUBLIC_URL}/images/home/true8d.svg`,
  VIN: `${PUBLIC_URL}/images/home/vinaphone.svg`,
  ARROW: `${PUBLIC_URL}/images/home/arrow.svg`,
  IMAGE1: `${PUBLIC_URL}/images/home/image1.png`,
  IMAGE2: `${PUBLIC_URL}/images/home/image2.png`,
  IMAGE3: `${PUBLIC_URL}/images/home/image3.png`,
  IMAGE4: `${PUBLIC_URL}/images/home/image4.png`,
  NEWS: `${PUBLIC_URL}/images/home/news.svg`,
  TV: `${PUBLIC_URL}/images/resource/TV.png`,
  VECTOR: `${PUBLIC_URL}/images/resource/vector.svg`,
  IMAGE: `${PUBLIC_URL}/images/resource/image1.svg`,
  LOGIN: `${PUBLIC_URL}/images/vector.jpg`,
  BLOGS: `${PUBLIC_URL}/images/resource/blogs.svg`,
  CASESTUDY: `${PUBLIC_URL}/images/resource/casestudy.svg`,
  DOCUMENTS: `${PUBLIC_URL}/images/resource/documents.svg`,
  VIDEOS: `${PUBLIC_URL}/images/resource/video.svg`,
  IMAGE_NEW1: `${PUBLIC_URL}/images/resource/image_new.svg`,
  IMAGE_BLOG1: `${PUBLIC_URL}/images/resource/image_blog.svg`,
  IMAGE_BLOG2: `${PUBLIC_URL}/images/resource/image_blog2.svg`,
  IMAGE_BLOG3: `${PUBLIC_URL}/images/resource/image_blog3.svg`,
  IMAGE_BLOG4: `${PUBLIC_URL}/images/resource/image_blog4.svg`,
  TV1: `${PUBLIC_URL}/images/products/multi_cdn/tv.png`,
  CHART: `${PUBLIC_URL}/images/products/multi_cdn/chart.svg`,
  CDN_A: `${PUBLIC_URL}/images/products/multi_cdn/cdn a.png`,
  CDN_B: `${PUBLIC_URL}/images/products/multi_cdn/cdn b.png`,
  CDN_C: `${PUBLIC_URL}/images/products/multi_cdn/cdn c.png`,
  CDN_D: `${PUBLIC_URL}/images/products/multi_cdn/cdn d.png`,
  CDN_E: `${PUBLIC_URL}/images/products/multi_cdn/cdn e.png`,
  CDN_F: `${PUBLIC_URL}/images/products/multi_cdn/cdn f.png`,
  CDN_G: `${PUBLIC_URL}/images/products/multi_cdn/cdn g.png`,
  CDN_H: `${PUBLIC_URL}/images/products/multi_cdn/cdn h.png`,
  RECTANGLE_2810: `${PUBLIC_URL}/images/products/multi_cdn/rectangle 2810.png`,
  RECTANGLE_2811: `${PUBLIC_URL}/images/products/multi_cdn/rectangle 2811.png`,
  RECTANGLE_2812: `${PUBLIC_URL}/images/products/multi_cdn/rectangle 2812.png`,
  RECTANGLE_2816: `${PUBLIC_URL}/images/products/multi_cdn/rectangle2816.png`,
  ARROW1: `${PUBLIC_URL}/images/products/multi_cdn/arrow1.svg`,
  DATA_SHEET: `${PUBLIC_URL}/images/products/multi_cdn/datasheet.svg`,
  FRAME_8: `${PUBLIC_URL}/images/products/multi_cdn/frame8.png`,
  FRAME_9: `${PUBLIC_URL}/images/products/multi_cdn/frame9.png`,
  FRAME_10: `${PUBLIC_URL}/images/products/multi_cdn/frame10.png`,
  FRAME_11: `${PUBLIC_URL}/images/products/multi_cdn/frame11.png`,
  FRAME_12: `${PUBLIC_URL}/images/products/multi_cdn/frame12.png`,
  FRAME_13: `${PUBLIC_URL}/images/products/multi_cdn/frame13.png`,
  TV_DAI: `${PUBLIC_URL}/images/products/sigma_dai/tv-dai.png`,
  TV_N53: `${PUBLIC_URL}/images/products/sigma_ns53/tv-n53.png`,
  TV_OTT: `${PUBLIC_URL}/images/service/ott/tv-ott.png`,
  TV_PACKAGE: `${PUBLIC_URL}/images/products/sigma_package/tv-package.png`,
  TV_TRANSCODER: `${PUBLIC_URL}/images/products/sigma_transcoder/tv-transcoder.png`,
  BLOCKERS_1: `${PUBLIC_URL}/images/products/sigma_dai/blockers1.png`,
  BLOCKERS_2: `${PUBLIC_URL}/images/products/sigma_dai/blockers2.png`,
  SIGMA_DAI_F1: `${PUBLIC_URL}/images/products/sigma_dai/sigmadai-f1.png`,
  SIGMA_DAI_F2: `${PUBLIC_URL}/images/products/sigma_dai/sigmadai-f2.png`,
  SIGMA_DAI_F3: `${PUBLIC_URL}/images/products/sigma_dai/sigmadai-f3.png`,
  SIGMA_DAI_F4: `${PUBLIC_URL}/images/products/sigma_dai/sigmadai-f4.png`,
  SIGMA_DAI_F5: `${PUBLIC_URL}/images/products/sigma_dai/sigmadai-f4.png`,
  SIGMA_DAI_F6: `${PUBLIC_URL}/images/products/sigma_dai/sigmadai-f6.png`,
  DNSCS: `${PUBLIC_URL}/images/products/sigma_ns53/dnscs.png`,
  N53_F1: `${PUBLIC_URL}/images/products/sigma_ns53/n53-f1.png`,
  N53_F2: `${PUBLIC_URL}/images/products/sigma_ns53/n53-f2.png`,
  N53_F3: `${PUBLIC_URL}/images/products/sigma_ns53/n53-f3.png`,
  N53_F4: `${PUBLIC_URL}/images/products/sigma_ns53/n53-f4.png`,
  N53_F5: `${PUBLIC_URL}/images/products/sigma_ns53/n53-f5.png`,
  N53_F6: `${PUBLIC_URL}/images/products/sigma_ns53/n53-f6.png`,
  DNSLB_1: `${PUBLIC_URL}/images/products/sigma_ns53/dnslb1.png`,
  DNSLB_2: `${PUBLIC_URL}/images/products/sigma_ns53/dnslb2.png`,
  DNSLB_3: `${PUBLIC_URL}/images/products/sigma_ns53/dnslb3.png`,
  W1: `${PUBLIC_URL}/images/products/sigma_transcoder/w1.png`,
  W2: `${PUBLIC_URL}/images/products/sigma_transcoder/w2.png`,
  W3: `${PUBLIC_URL}/images/products/sigma_transcoder/w3.png`,
  W4: `${PUBLIC_URL}/images/products/sigma_transcoder/w4.png`,
  W5: `${PUBLIC_URL}/images/products/sigma_transcoder/w5.png`,
  W6: `${PUBLIC_URL}/images/products/sigma_transcoder/w6.png`,
  PM1: `${PUBLIC_URL}/images/products/sigma_transcoder/pm1.png`,
  PM2: `${PUBLIC_URL}/images/products/sigma_transcoder/pm2.png`,
  PM3: `${PUBLIC_URL}/images/products/sigma_transcoder/pm3.png`,
  PM4: `${PUBLIC_URL}/images/products/sigma_transcoder/pm4.png`,
  PM5: `${PUBLIC_URL}/images/products/sigma_transcoder/pm5.png`,
  TRANS_W: `${PUBLIC_URL}/images/products/sigma_transcoder/trans-w.png`,
  LINE: `${PUBLIC_URL}/images/line.svg`,
  PACKAGE_W: `${PUBLIC_URL}/images/package-w.png`,
  PO1: `${PUBLIC_URL}/images/po1.png`,
  PO2: `${PUBLIC_URL}/images/po2.png`,
  PO3: `${PUBLIC_URL}/images/po3.png`,
  PO4: `${PUBLIC_URL}/images/po4.png`,
  PO5: `${PUBLIC_URL}/images/po5.png`,
  PO6: `${PUBLIC_URL}/images/po6.png`,
  P_MAC: `${PUBLIC_URL}/images/p-mac.png`,
  P_SOLUTION: `${PUBLIC_URL}/images/p-solution.png`,
  SIGMADAI_F1: `${PUBLIC_URL}/images/sigmadai-f1.png`,
  SIGMADAI_F2: `${PUBLIC_URL}/images/sigmadai-f2.png`,
  SIGMADAI_F3: `${PUBLIC_URL}/images/sigmadai-f3.png`,
  SIGMADAI_F4: `${PUBLIC_URL}/images/sigmadai-f4.png`,
  SIGMADAI_F5: `${PUBLIC_URL}/images/sigmadai-f4.png`,
  SIGMADAI_F6: `${PUBLIC_URL}/images/sigmadai-f6.png`,
  COMMENT: `${PUBLIC_URL}/images/comment.svg`,
  FRAME_1: `${PUBLIC_URL}/images/products/audio/frame1.png`,
  FRAME_2: `${PUBLIC_URL}/images/products/audio/frame2.png`,
  FRAME_3: `${PUBLIC_URL}/images/products/audio/frame3.png`,
  FRAME_4: `${PUBLIC_URL}/images/products/audio/frame4.png`,
  FRAME_5: `${PUBLIC_URL}/images/products/audio/frame5.png`,
  FRAME_6: `${PUBLIC_URL}/images/products/audio/frame6.png`,
  FRAME_7: `${PUBLIC_URL}/images/products/audio/frame7.png`,
  TV_AUDIO: `${PUBLIC_URL}/images/products/audio/tv.png`,
  IMAGE_AUDIO1: `${PUBLIC_URL}/images/products/audio/image1.png`,
  IMAGE_AUDIO2: `${PUBLIC_URL}/images/products/audio/image2.png`,
  IMAGE_AUDIO3: `${PUBLIC_URL}/images/products/audio/image3.png`,
  OTT_P1 : `${PUBLIC_URL}/images/service/ott/sigma-ott-p1.png`,
  OTT_P2 : `${PUBLIC_URL}/images/service/ott/sigma-ott-p2.png`,
  OTT_P3 : `${PUBLIC_URL}/images/service/ott/sigma-ott-p3.png`,
  OTT_P4 : `${PUBLIC_URL}/images/service/ott/sigma-ott-p4.png`,
  OTT_PROVIDES_1: `${PUBLIC_URL}/images/service/ott/ott-provides1.png`,
  OTT_PROVIDES_2: `${PUBLIC_URL}/images/service/ott/ott-provides2.png`,
  OTT_PROVIDES_3: `${PUBLIC_URL}/images/service/ott/ott-provides3.png`,
  OTT_PROVIDES_4: `${PUBLIC_URL}/images/service/ott/ott-provides4.png`,
  OTT_PROVIDES_5: `${PUBLIC_URL}/images/service/ott/ott-provides5.png`,
  OTT_PROVIDES_6: `${PUBLIC_URL}/images/service/ott/ott-provides6.png`,
  OTT_PROVIDES_7: `${PUBLIC_URL}/images/service/ott/ott-provides7.png`,
  OTT_PROVIDES_8: `${PUBLIC_URL}/images/service/ott/ott-provides8.png`,
  OTT_CLIENT: `${PUBLIC_URL}/images/service/ott/ott-client.png`,
  BOXES: `${PUBLIC_URL}/images/products/streaming/boxes.png`,
  CODING: `${PUBLIC_URL}/images/products/streaming/coding.png`,
  IMPORT: `${PUBLIC_URL}/images/products/streaming/import.png`,
  PLAY: `${PUBLIC_URL}/images/products/streaming/play.png`,
  FRAME14: `${PUBLIC_URL}/images/products/streaming/frame14.png`,
  FRAME15: `${PUBLIC_URL}/images/products/streaming/frame15.png`,
  FRAME16: `${PUBLIC_URL}/images/products/streaming/frame16.png`,
  FRAME17: `${PUBLIC_URL}/images/products/streaming/frame17.png`,
  FRAME18: `${PUBLIC_URL}/images/products/streaming/frame18.png`,
  FRAME19: `${PUBLIC_URL}/images/products/streaming/frame19.png`,
  IMAGE_STREAMING1: `${PUBLIC_URL}/images/products/streaming/image1.png`,
  IMAGE_STREAMING2: `${PUBLIC_URL}/images/products/streaming/image2.png`,
  IMAGE_STREAMING3: `${PUBLIC_URL}/images/products/streaming/image3.png`,
  IMAGE_STREAMING4: `${PUBLIC_URL}/images/products/streaming/image4.png`,
};
