import { PUBLIC_URL } from 'src/configs';

export const IMAGE_PATH = {
  LOGO_FOOTER: `${PUBLIC_URL}/images/logo-footer.svg`,
  LOGO_ORANGE: `${PUBLIC_URL}/images/logo-orange.svg`,
  LOGO_WHITE: `${PUBLIC_URL}/images/logo-white.svg`,
  USA: `${PUBLIC_URL}/images/usa.svg`,
  VN: `${PUBLIC_URL}/images/vn.svg`,
  VIDEO: `${PUBLIC_URL}/images/home/video.svg`,
  ITEM1: `${PUBLIC_URL}/images/home/item1.svg`,
  ITEM2: `${PUBLIC_URL}/images/home/item2.svg`,
  ITEM3: `${PUBLIC_URL}/images/home/item3.svg`,
  ITEM4: `${PUBLIC_URL}/images/home/item4.svg`,
  ITEM5: `${PUBLIC_URL}/images/home/item5.svg`,
  ITEM6: `${PUBLIC_URL}/images/home/item6.svg`,
  ITEM7: `${PUBLIC_URL}/images/home/item7.svg`,
  ITEM8: `${PUBLIC_URL}/images/home/item8.svg`,
  ITEM9: `${PUBLIC_URL}/images/home/item9.svg`,
  POLYGON: `${PUBLIC_URL}/images/home/polygon.png`,
  AWARD: `${PUBLIC_URL}/images/home/award.svg`,
  VTV: `${PUBLIC_URL}/images/home/vtvcab.svg`,
  VIETTEL: `${PUBLIC_URL}/images/home/viettel.svg`,
  TRUE: `${PUBLIC_URL}/images/home/true8d.svg`,
  VIN: `${PUBLIC_URL}/images/home/vinaphone.svg`,
  ARROW: `${PUBLIC_URL}/images/home/arrow.svg`,
  IMAGE1: `${PUBLIC_URL}/images/home/image1.png`,
  IMAGE2: `${PUBLIC_URL}/images/home/image2.png`,
  IMAGE3: `${PUBLIC_URL}/images/home/image3.png`,
  IMAGE4: `${PUBLIC_URL}/images/home/image4.png`,
  NEWS: `${PUBLIC_URL}/images/home/news.svg`,
  TV: `${PUBLIC_URL}/images/resource/TV.png`,
  VECTOR: `${PUBLIC_URL}/images/resource/vector.svg`,
  IMAGE: `${PUBLIC_URL}/images/resource/image1.svg`,
  LOGIN: `${PUBLIC_URL}/images/vector.jpg`,
  BLOGS: `${PUBLIC_URL}/images/resource/blogs.svg`,
  CASESTUDY: `${PUBLIC_URL}/images/resource/casestudy.svg`,
  DOCUMENTS: `${PUBLIC_URL}/images/resource/documents.svg`,
  VIDEOS: `${PUBLIC_URL}/images/resource/video.svg`,
  IMAGE_NEW1: `${PUBLIC_URL}/images/resource/image_new.svg`,
  IMAGE_BLOG1: `${PUBLIC_URL}/images/resource/image_blog.svg`,
  IMAGE_BLOG2: `${PUBLIC_URL}/images/resource/image_blog2.svg`,
  IMAGE_BLOG3: `${PUBLIC_URL}/images/resource/image_blog3.svg`,
  IMAGE_BLOG4: `${PUBLIC_URL}/images/resource/image_blog4.svg`,
  TV1: `${PUBLIC_URL}/images/products/tv.png`,
  CHART: `${PUBLIC_URL}/images/products/chart.svg`,
  CDN_A: `${PUBLIC_URL}/images/products/cdn a.png`,
  CDN_B: `${PUBLIC_URL}/images/products/cdn b.png`,
  CDN_C: `${PUBLIC_URL}/images/products/cdn c.png`,
  CDN_D: `${PUBLIC_URL}/images/products/cdn d.png`,
  CDN_E: `${PUBLIC_URL}/images/products/cdn e.png`,
  CDN_F: `${PUBLIC_URL}/images/products/cdn f.png`,
  CDN_G: `${PUBLIC_URL}/images/products/cdn g.png`,
  CDN_H: `${PUBLIC_URL}/images/products/cdn h.png`,
  FRAME_1: `${PUBLIC_URL}/images/products/frame 50.png`,
  FRAME_2: `${PUBLIC_URL}/images/products/frame 51.png`,
  RECTANGLE_2810: `${PUBLIC_URL}/images/products/rectangle 2810.png`,
  RECTANGLE_2811: `${PUBLIC_URL}/images/products/rectangle 2811.png`,
  RECTANGLE_2812: `${PUBLIC_URL}/images/products/rectangle 2812.png`,
  RECTANGLE_2816: `${PUBLIC_URL}/images/products/rectangle2816.png`,
  ARROW1: `${PUBLIC_URL}/images/products/arrow1.svg`,
  DATA_SHEET: `${PUBLIC_URL}/images/products/datasheet.svg`,
};
