import { IMAGE_PATH } from 'src/constants/images';

export const news = [
  {
    title: 'Content Packages1',
    id: '1',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    option: 'new',
  },
  {
    title: 'Content Packages2',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages3',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages4',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages5',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages6',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages7',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages8',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages9',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages10',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages11',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages12',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages13',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages14',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages15',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages16',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages17',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages18',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages19',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages20',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages21',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages22',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages23',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages24',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages25',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages26',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages27',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
  {
    title: 'Content Packages28',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1',
    option: 'new',
  },
];
export const blogs = [
  {
    title: 'Content Packages1',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages2',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages3',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages4',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages5',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages6',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages7',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages8',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages9',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages10',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages11',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages12',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages13',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages14',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages15',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages16',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages17',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages18',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages19',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
  {
    title: 'Content Packages20',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1blog',
    option: 'blog',
  },
];
export const videos = [
  {
    title: 'Content Packages1',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages2',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages3',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages4',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages5',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages6',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages7',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages8',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages9',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages10',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages11',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages12',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages13',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages14',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages15',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages16',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages17',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages18',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages19',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages20',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages21',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages22',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages23',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages24',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
  {
    title: 'Content Packages25',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1video',
    option: 'video',
  },
];
export const documents = [
  {
    title: 'Content Packages1',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages2',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages3',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages4',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages5',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages6',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages7',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages8',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages9',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages10',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages11',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages12',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages13',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages14',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages15',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages16',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages17',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages18',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
  {
    title: 'Content Packages19',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'document',
  },
];
export const casestudy = [
  {
    title: 'Content Packages1',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages2',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages3',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages4',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages5',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages6',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages7',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages8',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages9',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages10',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages11',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages12',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages13',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages14',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages15',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages16',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages17',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages18',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages19',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages20',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages21',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages22',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages23',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages24',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages25',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
  {
    title: 'Content Packages26',
    url: '#',
    image: IMAGE_PATH.IMAGE,
    id: '1a',
    option: 'casestudy',
  },
];
