import { IMAGE_PATH } from 'src/constants/images';

export const resource = [
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.ABOUT_US,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
