import { IMAGE_PATH } from 'src/constants/images';

export const resource = [
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdqwdqw1",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.IMAGE_BLOG4,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'new',
    thumbnail: IMAGE_PATH.ABOUT_US,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'blog',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'video',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'document',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
  {
    id: "dqwdq23112",
    author: 'admin',
    title: 'All industry standard layout formats',
    content: 'All industry standard layout formats',
    description: 'All industry standard layout formats',
    category: 'casestudy',
    thumbnail: IMAGE_PATH.IMAGE_BLOG3,
  },
];
